//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoxarifadoUpas.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoMovimentacao
    {
        public int id_movimento { get; set; }
        public string origem { get; set; }
        public string destino { get; set; }
        public Nullable<int> quantidade { get; set; }
        public int id_materialA { get; set; }
        public string tipoMovimentacao { get; set; }
    
        public virtual MaterialA MaterialA { get; set; }
    }
}
